---
- hosts: deploy
  become: yes
#  become_user: ansible
  become_method: sudo
#  user: ansible
  gather_facts: yes
  tasks:
  - name: copy
    copy: 
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
     owner: root
     group: root
     backup: yes
    with_items:
      - { src: 'files/network', dest: '/etc/sysconfig/network' }
      - { src: 'files/resolv.conf', dest: '/etc/resolv.conf' }
  - name: test
    template: src=ifcfg-eth0.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth0 backup=yes
    notify:
     - network restart

  handlers:
  - name: network restart
    service: name=network state=restarted

